from src.entities_extractor import entity_from_huristics, entity_from_tfidf

new_entity_list = []

def findEntities(scenario):
    return entity_from_huristics.preprocess_data(scenario)
    #scenario= "Patients are identified by an SSN, and their names, addresses, and ages must be recorded. Doctors are identified by an SSN. For each doctor, the name, specialty, and years of experience must be recorded. Each pharmaceutical company is identified by name and has a phone number. For each drug, the trade name and formula must be recorded. Each drug is sold by a given pharmaceutical company, and the trade name identifies a drug uniquely from among the products of that company. If a pharmaceutical company is deleted, you need not keep track of its products any longer. Each pharmacy has a name, address, and phone number. Every patient has a primary physician. Every doctor has at least one patient. Each pharmacy sells several drugs and has a price for each. A drug could be sold at several pharmacies, and the price could vary from one pharmacy to another. Doctors prescribe drugs for patients. A doctor could prescribe one or more drugs for several patients, and a patient could obtain prescriptions from several doctors. Each prescription has a date and a quantity associated with it.  You can assume that, if a doctor prescribes the same drug for the same patient more than once, only the last such prescription needs to be stored. Pharmaceutical companies have long-term contracts with pharmacies."
    #scenario= "Each musician that records at Notown has an SSN, a name, an address, and a phone number. Poorly paid musicians often share the same address, and no address has more than one phone. Each instrument used in songs recorded at Notown has a unique identification number, a name (e.g., guitar, synthesizer, flute) and a musical key (e.g., C, B-flat, E-flat). Each album recorded on the Notown label has a unique identification number, a title, a copyright date, a format (e.g., CD or MC), and an album identifier. Each song recorded at Notown has a title and an author. Each musician may play several instruments, and a given instrument may be played by several musicians. Each album has a number of songs on it, but no song may appear on more than one album. Each song is performed by one or more musicians, and a musician may perform a number of songs. Each album has exactly one musician who acts as its producer. A musician may produce several albums, of course."
    #scenario= "The league is run for teams, which are identified by their names. Each team has one or more drivers signed up, and each driver is registered with the league and has a unique league licence number. First and last names of the drivers should also be included. A driver may only participate for a single team throughout the season. Races are identified simply by the dates when they are run. For each race, the league also wants to store the venue where it took place. Drivers participate in races, and for each participating driver the database should store the total race time for that driver, and the league score they got from that race."
    #scenario= "Professors have an SSN, a name, an age, a rank, and a research specialty. Projects have a project number, a sponsor name (e.g., NSF), a starting date, an ending date, and a budget. Graduate students have an SSN, a name, an age, and a degree program (e.g., M.S. or Ph.D.). Each project is managed by one professor (known as the project’s principal investigator). Each project is worked on by one or more professors (known as the project’s co-investigators). Professors can manage and/or work on multiple projects. Each project is worked on by one or more graduate students (known as the project’s research assistants). When graduate students work on a project, a professor must supervise their work on the project. Graduate students can work on multiple projects, in which case they will have a (potentially different) supervisor for each one. Departments have a department number, a department name, and a main office. Departments have a professor (known as the chairman) who runs the department. Professors work in one or more departments, and for each department that they work in, a time percentage is associated with their job. Graduate students have one major department in which they are working on their degree. Each graduate student has another, more senior graduate student (known as a student advisor) who advises him or her on what courses to take."
    #scenario= "Shipped items are the heart of the UPS product tracking information system. Shipped items can be characterized by item number (unique), weight, dimensions, insurance amount, destination, and final delivery date. Shipped items are received into the UPS system at a single retail center. Retail centers are characterized by their type, uniqueID, and address. Shipped items make their way to their destination via one or more standard UPS transportation events (i.e., flights, truck deliveries). These transportation events are characterized by a unique scheduleNumber, a type (e.g, flight, truck), and a deliveryRoute."
    #scenario= "The EST university has three Faculties, Education, Science and Information Technology. Each faculty can offer one or more degree programs. The faculty of Education and the Faculty of Science offer Bachelor of Education and Bachelor of Science degree programs respectively. However,the Faculty of Information Technology. Offers two degree programs: Bachelor of Science in information Technology and Bachelor of Science in Software Engineering. At the time of registration, students should pay the full degree program fee which may differ from one degree program to another. A student can enroll in only one degree program at a time. A degree program has two type of course units: compulsory and optional. A course unit can be available in more than one degree program. EST university has many lectures. A lecturer can be assigned to one or more course units. A course unit can be assigned to one or more lecturers. Number of hours allocated for a course unit distributed among the assigned lectures when more than one lecturer is assigned to a course unit. Each faculty, degree program, course unit, lecturer, and student are uniquely identified by facultyID’, ‘degreeID’ , ‘courseID’, ‘lecturerID’ and ‘studentID’ respectively."
    #scenario= "The collection consists of albums. An album is made by exactly one artist. An artist makes one or more albums. An album contains one or more tracks. Artists, albums, and tracks each have a name. Each track is on exactly one album. Each track has a time length, measured in seconds. When a track is played, the date and time the playback began (to the nearest second) should be recorded; this is used for reporting when a track was last played, as well as the number of times music by an artist, from an album, or a track has been played. There’s no requirement to capture composers, group members or sidemen, recording date or location, the source media, or any other details of artists, albums, or tracks."
    #scenario= "The university offers one or more programs. A program is made up of one or more courses. A student must enroll in a program. A student takes the courses that are part of her program. A program has a name, a program identifier, the total credit points required to graduate, and the year it commenced. A course has a name, a course identifier, a credit point value, and the year it commenced. Students have one or more given names, a surname, a student identifier, a date of birth, and the year they first enrolled. We can treat all given names as a single object—for example, John Paul. When a student takes a course, the year and semester he attempted it are recorded. When he finishes the course, a grade (such as A or B) and a mark (such as 60 percent) are recorded. Each course in a program is sequenced into a year (for example, year 1) and a semester (for example, semester 1)."
    #scenario= "Every airplane has a registration number. Each airplane belongs to a specific model. The airport accommodates a number of airplane models and each model is identified by a model number (e.g. DC-10) and has a capacity and a weight. A number of technicians work at the airport. You need to store the name, NIC, address, phone number, and salary of each technician. You can assume that each technician is uniquely identified by a national identity card (NIC) number. Each technician is an expert on one or more plane model(s), and his or her expertise may overlap with that of other technicians. This information about technicians must also be recorded. The airport has a number of test types, that are used periodically to ensure that airplanes are still airworthy. Each test type has Federal Aviation Administration (FAA) test number, a name, and a maximum possible score The FAA requires the airport to keep track of each time a given airplane is tested by a given technician using a given test. For each testing event, the information needed is the date and time, the number of hours the technician spent doing the test, and the score the airplane received on the test. For a given plane, several test types can be done parallel for a particular time."
    #entity_from_huristics.preprocess_data(scenario)



